development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sanjose_dev
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sanjose_prod
  pool: 5
  username: root
  password: 